-- Lecture Diary Schema for Turso
-- Run this SQL in your Turso database console

CREATE TABLE IF NOT EXISTS Student (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  grade INTEGER NOT NULL,
  board TEXT NOT NULL,
  field TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'paid',
  startDate DATETIME NOT NULL,
  targetDate DATETIME NOT NULL,
  currentDay INTEGER NOT NULL DEFAULT 1,
  totalDays INTEGER NOT NULL,
  topicsDone INTEGER NOT NULL DEFAULT 0,
  daysLeft INTEGER NOT NULL,
  pacingGoal TEXT NOT NULL DEFAULT '5M',
  pin TEXT NOT NULL DEFAULT '1234',
  academicGroup TEXT NOT NULL DEFAULT '',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Subject (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  grade TEXT NOT NULL,
  board TEXT NOT NULL,
  field TEXT NOT NULL,
  totalTopics INTEGER NOT NULL,
  chapterCount INTEGER NOT NULL,
  color TEXT NOT NULL,
  icon TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0,
  groupEligibility TEXT NOT NULL DEFAULT 'Both',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Chapter (
  id TEXT PRIMARY KEY NOT NULL,
  subjectId TEXT NOT NULL,
  number INTEGER NOT NULL,
  name TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (subjectId) REFERENCES Subject(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Topic (
  id TEXT PRIMARY KEY NOT NULL,
  chapterId TEXT NOT NULL,
  number INTEGER NOT NULL,
  name TEXT NOT NULL,
  videoLink TEXT NOT NULL DEFAULT '',
  pdfLink TEXT NOT NULL DEFAULT '',
  isFree BOOLEAN NOT NULL DEFAULT true,
  dayNumber INTEGER NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chapterId) REFERENCES Chapter(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Progress (
  id TEXT PRIMARY KEY NOT NULL,
  topicId TEXT NOT NULL,
  studentPhone TEXT NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT false,
  dateCompleted DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (topicId) REFERENCES Topic(id) ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE(topicId, studentPhone)
);

CREATE TABLE IF NOT EXISTS SpecialCourse (
  id TEXT PRIMARY KEY NOT NULL,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  topic TEXT NOT NULL,
  videoLink TEXT NOT NULL DEFAULT '',
  pdfLink TEXT NOT NULL DEFAULT '',
  grade TEXT NOT NULL,
  board TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Config (
  id TEXT PRIMARY KEY NOT NULL,
  key TEXT NOT NULL UNIQUE,
  value TEXT NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS Chapter_subjectId_idx ON Chapter(subjectId);
CREATE INDEX IF NOT EXISTS Topic_chapterId_idx ON Topic(chapterId);
CREATE INDEX IF NOT EXISTS Progress_topicId_idx ON Progress(topicId);
CREATE INDEX IF NOT EXISTS Progress_studentPhone_idx ON Progress(studentPhone);
